# Launches a cloud VM, builds the app, starts MySQL + virtual desktop + noVNC, and runs your JavaFX GUI.
image:
  file: .gitpod/Dockerfile

ports:
  - port: 6080
    onOpen: open-browser
    visibility: public
    name: GUI (noVNC)
  - port: 3306
    visibility: private
    name: MySQL

tasks:
  - name: Init & Run
    init: |
      mvn -B -DskipTests package
    command: |
      bash scripts/start.sh
