# .gitpod.yml
image: gitpod/workspace-full-vnc

ports:
  - port: 6080
    onOpen: open-preview   # web desktop (noVNC)
  - port: 3306
    onOpen: ignore

tasks:
  - name: Setup & DB
    init: |
      docker compose up -d db
      bash scripts/setup.sh
    command: |
      bash scripts/run.sh
