version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankmanagement
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 3s
      timeout: 2s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: bms-app
    environment:
      DB_URL: jdbc:mysql://db:3306/bankmanagement?useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASS: root
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  db_data:
